# apiVersion: v1
# kind: Service
# metadata:
#   name: payment-microservice-service
# spec:
#   type: NodePort
#   ports:
#   - port: 5001
#     targetPort: 5001
#     nodePort: 30002
#   selector:
#     app: payment-microservice

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-microservice
  template:
    metadata:
      labels:
        app: payment-microservice
    spec:
      containers:
      - name: payment-microservice
        image: payment-microservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: FLASK_ENV
          value: development
---
apiVersion: v1
kind: Service
metadata:
  name: payment-microservice-service
spec:
  type: NodePort
  selector:
    app: payment-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001